Repository PMBio/deeprvat, pull requests merged in 2024-05, with the labels that each got.

#80 Update environment_spliceai_rocksdb.yaml
  pipelines/resources/environment_spliceai_rocksdb.yaml
Labels: bug

#98 Add checks for empty samples and variants
  deeprvat/preprocessing/preprocess.py
  tests/preprocessing/test_data/process_sparse_gt/filter_samples_all/expected/expected_data.npz
  tests/preprocessing/test_data/process_sparse_gt/filter_samples_all/input/qc/excluded_samples.csv
  tests/preprocessing/test_data/process_sparse_gt/filter_samples_all/input/samples_chr.csv
  tests/preprocessing/test_data/process_sparse_gt/filter_samples_all/input/sparse_gt/chr1/input_c1_b1.tsv.gz
  tests/preprocessing/test_data/process_sparse_gt/filter_samples_all/input/variants.parquet
  tests/preprocessing/test_data/process_sparse_gt/filter_samples_all/input/variants.tsv.gz
  tests/preprocessing/test_data/process_sparse_gt/filter_variants_all/expected/expected_data.npz
  tests/preprocessing/test_data/process_sparse_gt/filter_variants_all/input/qc/input_c1_b1.tsv
  tests/preprocessing/test_data/process_sparse_gt/filter_variants_all/input/samples_chr.csv
  tests/preprocessing/test_data/process_sparse_gt/filter_variants_all/input/sparse_gt/chr1/input_c1_b1.tsv.gz
  tests/preprocessing/test_data/process_sparse_gt/filter_variants_all/input/variants.parquet
  tests/preprocessing/test_data/process_sparse_gt/filter_variants_all/input/variants.tsv.gz
  tests/preprocessing/test_preprocess.py
Labels: enhancement

#93 Refactor and add test actions
  .github/workflows/code-tests.yml
  .github/workflows/github-actions.yml
  .github/workflows/pipeline-tests.yml
  .github/workflows/run-pipeline.yml
  .github/workflows/run-pytest.yml
  .github/workflows/test-runner.yml
Labels: enhancement

#101 Absplice named env
  deeprvat/annotations/annotations.py
  deeprvat/annotations/setup_annotation_workflow.sh
  docs/annotations.md
  pipelines/annotations.snakefile
  pipelines/config/deeprvat_annotation_config.yaml
  pipelines/resources/absplice.yaml
  pipelines/resources/absplice_download.snakefile
  pipelines/resources/absplice_splicing_pred_DNA.snakefile
  pipelines/resources/environment_spliceai_rocksdb.yaml
  tests/annotations/test_annotations.py
  tests/annotations/test_data/merge_absplice_scores/merge_absplice_scores_exons/expected/vep_deepripe_deepsea_absplice.parquet
  tests/annotations/test_data/merge_absplice_scores/merge_absplice_scores_exons/input/abSplice_score_file.parquet
  tests/annotations/test_data/merge_absplice_scores/merge_absplice_scores_exons/input/vep_deepripe_deepsea.parquet
Labels: enhancement

#105 changed config to use normalized bcfs as default input.
  pipelines/config/deeprvat_annotation_config.yaml
Labels: documentation
